
dirs:
  run: "runs"
  logs: "logs"

# Add any other dataset-specific configurations here
dataset:
  # Always include the background as a class
  mapping_dict:
    -1: 0
    0: 0
    1: 1
    2: 1  # sidewalk
    3: 2  # building
    4: 2  # wall
    5: 2  # fence
    6: 0  # pole
    7: 3  # traffic_light
    8: 3  # traffic_sign
    9: 4  # vegetation
    10: 5  # terrain
    11: 6  # sky
    12: 7  # person
    13: 7  # rider
    14: 8  # car
    15: 9  # truck
    16: 9  # bus
    17: 9  # train
    18: 10  # motorcycle
    19: 0  # bicycle  It seems there are no bikes in this dataset
  classes: 
    'background': 0
    'road': 1
    'structure': 2
    'traffic_sign': 3
    'vegetation': 4
    'terrain': 5
    'sky': 6
    'person': 7
    'car': 8
    'large_vehicle': 9
    'motorcycle': 10
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  height: 128
  width: 256

# Some training hyperparameters
training:
  epochs: 5
  batch_size: 8
  encoder_name: "efficientnet-b3"
  initial_learning_rate: 1e-3
  loss: "cross_entropy"

evaluation:
  metrics: [iou, f1, precision, recall, accuracy]
  reduction_mode: ["macro", "none"]
